apiVersion: v1
kind: Service
metadata:
  name: hub-proxy-lb
  namespace: d4n-analytics
spec:
  ports:
  - name: httplb
    appProtocol: http
    port: 8080
    targetPort: http
  selector:
    app: jupyterhub
    component: proxy
    release: jupyter
  type: LoadBalancer
status:
  loadBalancer: {}
