apiVersion: v1
kind: Service
metadata:
  name: public-proxy-console
spec:
  type: NodePort
  selector:
    app : minio # label of the pod
  ports:
    - name: noteportconsole
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30901

---
apiVersion: v1
kind: Service
metadata:
  name: public-proxy
spec:
  type: NodePort
  selector:
    app : minio # label of the pod
  ports:
    - name: noteportapi
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
