apiVersion: v1
kind: Service
metadata:
  name: nifi-lb
  namespace: d4n-ingestion
spec:
  ports:
  - name: httplb
    appProtocol: https
    port: 8443
    targetPort: 8443
  selector:
    app: nifi
    release: nifi
  type: LoadBalancer
status:
  loadBalancer: {}