apiVersion: v1
kind: Service
metadata:
  name: public-proxy
spec:
  type: NodePort
  selector:
    app : nifi
  ports:
    - name: nodeport
      port: 8443
      targetPort: 8443
      nodePort: 30443
