apiVersion: v1
kind: Service
metadata:
  name: hub-proxy-lb
  namespace: d4n-analytics
spec:
  ports:
  - name: httplb
    appProtocol: http
    port: 8080
    targetPort: http
  selector:
    app: jupyterhub
    component: proxy
    release: jupyter
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-lb
  namespace: d4n-storage
spec:
  ports:
  - name: httplb
    port: 9001
    targetPort: 9001
  selector:
    app: minio
    release: minio
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-lb
  namespace: d4n-ingestion
spec:
  ports:
  - name: httplb
    appProtocol: https
    port: 8443
    targetPort: 8443
  selector:
    app: nifi
    release: nifi
  type: LoadBalancer
status:
  loadBalancer: {}