apiVersion: v1
kind: Service
metadata:
  name: long-proxy-console
  namespace: longhorn-system
spec:
  type: NodePort
  selector:
    app : longhorn-ui # label of the pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
